# THIS DOCKERFILE IS ONLY INTENDED FOR TESTING
version: '3.7'
networks:
  docker-network:
services:
  frontend_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 5000
    ports:
      - '5000:5000'
